server:
  port: 9999

spring:
  #  数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/x-admin-template?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
#    host: ${SPRING_REDIS_HOST}
#    port: ${SPRING_REDIS_PORT}
    host: localhost
    port: 6379
  logging:
    level:
      com.ziling.xaming: DEBUG
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# MyBatis-Plus 日志打印配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台输出SQL日志
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除字段名
      logic-delete-value: 1 # 逻辑已删除值。可选，默认值为 1
      logic-not-delete-value: 0 # 逻辑未删除值。可选，默认值为 0
  type-aliases-package: com.ziling.xadmin.entity
  mapper-locations: classpath*:/mapper/**/*.xml

logging:
  level:
    com.ziling.xaming: DEBUG
    com.baomidou.mybatisplus: DEBUG      # 打印 MyBatis-Plus 的日志
    org.apache.ibatis: DEBUG