# application-prod.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/x-admin-template?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

  redis:
    host: localhost
    port: 6379